apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metabase
  source:
    repoURL: https://github.com/goegoe0212/home-kubernetes.git
    path: apps/metabase/overlays
    targetRevision: HEAD
    kustomize: {}