apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  source:
    repoURL: https://github.com/goegoe0212/home-kubernetes.git
    path: apps/minecraft/overlays
    targetRevision: HEAD
    kustomize: {}