apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../secret

  - application-postgresql.yaml
  - application-redis.yaml

  - application-minecraft.yaml
  - application-immich.yaml
  - application-home-api.yaml
  - application-temp-collector.yaml
  - application-discord-bot.yaml
  - application-metabase.yaml

  - application-cloudflare.yaml
