apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
- namespace.yaml
- ../base

images:
  - name: ghcr.io/immich-app/postgres
    newTag: 14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: release
  - name: ghcr.io/immich-app/immich-server
    newTag: release
  - name: docker.io/valkey/valkey
    newTag: 9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63