apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discord-bot

resources:
- namespace.yaml
- discord-bot-configmap.yaml
- sealedsecret.yaml
- ../base

images:
- name: goegoe0212/home-discord-bot
  newTag: 0.1.1