apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application-home-app.yaml
  - application-postgresql.yaml
  - application-minecraft.yaml
  - application-cloudflare.yaml
  - ../../secret
