apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - immich-pvc.yaml
  - database-deploy.yaml
  - redis-deploy.yaml
  - immich-server-deploy.yaml
  - immich-machine-learning-deploy.yaml


